Repository GSG-FC03/Team3-ToDoApp, pull requests merged in 2021-07, with the labels that each got.

#3 created file structure
  css/MainStyle.css
  css/Media.css
  css/style.css
  html/toDoLists.html
  index.html
  js/main.js
Labels: approved

#5 4 change style file name
  css/toDoStyle.css
  html/toDoLists.html
  index.html
Labels: approved

#8 Create main html css #7
  css/style.css
  index.html
Labels: approved

#6 1 create readmefile
  README.md
Labels: approved

#13 Modify structure #11
  css/style.css
  css/toDoStyle.css
  html/toDoLists.html
  index.html
  js/main.js
Labels: Waiting-Review

#16 Change FAB Button Position
  css/toDoStyle.css
Labels: approved

#20 Create dom.js file
  js/dom.js
Labels: approved

#19 14 create js for main page
  css/toDoStyle.css
  html/toDoLists.html
  index.html
  js/main.js
Labels: approved

#31 28 get data from local storage
  css/toDoStyle.css
  html/toDoLists.html
  index.html
  js/dom.js
  js/main.js
Labels: in_progress

#40 Deleting Done Button
  css/toDoStyle.css
  html/toDoLists.html
  js/dom.js
  js/main.js
Labels: Waiting-Review

#42 41 app update for to do
  css/toDoStyle.css
  js/main.js
  my code/.vscode/settings.json
  my code/css/style.css
  my code/css/toDo.css
  my code/img/ico - 24 - actions - add.svg
  my code/img/ico - 24 - actions - done.svg
  my code/img/welcome.svg
  my code/index.html
  my code/js/logIn.js
  my code/js/main.js
  my code/toDo.html
Labels: update
